# Generated by Django 4.1.7 on 2023-03-02 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ess_app', '0004_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.CharField(default=None, max_length=45)),
                ('sender_id', models.CharField(default=None, max_length=45)),
                ('subject', models.CharField(default=None, max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('receiver_status', models.BooleanField(default=True, null=True)),
                ('sender_status', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
