# Generated by Django 4.1.7 on 2023-03-07 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ess_app', '0005_user_message_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('user_id', models.CharField(default=None, max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=45)),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=100)),
                ('address', models.TextField()),
                ('experience', models.CharField(default=None, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_id', models.CharField(default=None, max_length=45)),
                ('tips_content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
