# Generated by Django 4.1.7 on 2023-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_app', '0007_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(default=None, max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=45)),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
