# Generated by Django 4.1.7 on 2023-03-27 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ess_app', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=45)),
                ('property_type', models.CharField(default=None, max_length=45)),
                ('rent_price', models.CharField(default=None, max_length=100)),
                ('facilities', models.TextField()),
                ('city', models.CharField(default=None, max_length=100)),
                ('address', models.TextField()),
                ('contact', models.CharField(default=None, max_length=100)),
                ('picture', models.FileField(default='', upload_to='ess_app/photo')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
